language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libxml2-dev
install:
    - composer install
script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml
after_success:
    - travis_rerty php vendor/bin/coveralls -v
